const cities = ["Alba Iulia","Arad","Bacău","Baia Mare","Botoșani","Brăila","Brașov","București","Buzău","Cluj-Napoca","Constanța","Craiova","Deva","Drobeta-Turnu Severin","Focșani","Galați","Hunedoara","Iași","Mediaș","Miercurea-Ciuc","Onești","Oradea","Piatra Neamț","Pitești","Ploiești","Râmnicu Vâlcea","Reșița","Roman","Satu Mare","Sfântu Gheorghe","Sibiu","Sighișoara","Slatina","Suceava","Târgoviște","Târgu Mureș","Tecuci","Timișoara","Tulcea","Vaslui","Zalău"];
const normalize = value => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ș/g,"s").replace(/ț/g,"t").toLowerCase().replace(/[-\s]/g, "");
const cityModal = document.querySelector('#city-modal');
const authModal = document.querySelector('#auth-modal');
const cityPoints = {"Alba Iulia":[174,265],"Arad":[78,205],"Bacău":[326,198],"Baia Mare":[178,102],"Botoșani":[395,83],"Brăila":[376,316],"Brașov":[238,242],"București":[284,354],"Buzău":[303,284],"Cluj-Napoca":[194,151],"Constanța":[407,359],"Craiova":[153,352],"Deva":[146,240],"Drobeta-Turnu Severin":[99,331],"Focșani":[334,267],"Galați":[373,299],"Hunedoara":[132,255],"Iași":[400,171],"Mediaș":[205,218],"Miercurea-Ciuc":[274,204],"Onești":[299,216],"Oradea":[120,151],"Piatra Neamț":[349,168],"Pitești":[213,323],"Ploiești":[276,302],"Râmnicu Vâlcea":[194,289],"Reșița":[106,271],"Roman":[364,190],"Satu Mare":[134,73],"Sfântu Gheorghe":[252,224],"Sibiu":[190,250],"Sighișoara":[225,205],"Slatina":[182,341],"Suceava":[360,104],"Târgoviște":[250,305],"Târgu Mureș":[227,184],"Tecuci":[351,280],"Timișoara":[82,255],"Tulcea":[410,301],"Vaslui":[402,218],"Zalău":[154,126]};
const map = document.querySelector('#romania-map');
const cityCodes = {"Alba Iulia":"AB","Arad":"AR","Bacău":"BC","Baia Mare":"MM","Botoșani":"BT","Brăila":"BR","Brașov":"BV","București":"B","Buzău":"BZ","Cluj-Napoca":"CJ","Constanța":"CT","Craiova":"DJ","Deva":"HD","Drobeta-Turnu Severin":"MH","Focșani":"VN","Galați":"GL","Hunedoara":"HD","Iași":"IS","Mediaș":"SB","Miercurea-Ciuc":"HR","Onești":"BC","Oradea":"BH","Piatra Neamț":"NT","Pitești":"AG","Ploiești":"PH","Râmnicu Vâlcea":"VL","Reșița":"CS","Roman":"NT","Satu Mare":"SM","Sfântu Gheorghe":"CV","Sibiu":"SB","Sighișoara":"MS","Slatina":"OT","Suceava":"SV","Târgoviște":"DB","Târgu Mureș":"MS","Tecuci":"GL","Timișoara":"TM","Tulcea":"TL","Vaslui":"VS","Zalău":"SJ"};
const inactivePoints = {"Bistrița":[260,127],"Târgu Jiu":[164,325],"Călărași":[324,358],"Giurgiu":[266,372],"Slobozia":[354,333],"Alexandria":[227,370]};
function addMapPoint(name, coordinates, state) { const [x, y] = coordinates; const code = cityCodes[name] || name.slice(0, 2).toUpperCase(); const point = document.createElement('button'); point.type = 'button'; point.className = `map-pin ${state}`; point.style.left = `${(x / 500) * 100}%`; point.style.top = `${(y / 440) * 100}%`; point.setAttribute('aria-label', `${name}: ${state === 'active' ? 'activ' : 'neactiv momentan'}`); point.innerHTML = `<span>${code}</span><b>${state === 'active' ? '✓' : '×'}</b>`; const select = () => { const input = document.querySelector('#city-input'); input.value = name; cityModal.showModal(); document.querySelector('#city-form').requestSubmit(); }; point.addEventListener('click', select); map.append(point); }
Object.entries(cityPoints).forEach(([name, coordinates]) => addMapPoint(name, coordinates, 'active'));
Object.entries(inactivePoints).forEach(([name, coordinates]) => addMapPoint(name, coordinates, 'inactive'));
document.querySelectorAll('[data-open-city]').forEach(button => button.addEventListener('click', () => { cityModal.showModal(); document.querySelector('#city-input').focus(); }));
document.querySelectorAll('.close').forEach(button => button.addEventListener('click', () => button.closest('dialog').close()));
document.querySelector('#city-form').addEventListener('submit', event => { event.preventDefault(); const input = document.querySelector('#city-input'); const result = document.querySelector('#city-result'); const city = cities.find(item => normalize(item) === normalize(input.value.trim())); result.className = `city-result ${city ? 'yes' : 'no'}`; result.innerHTML = city ? `<strong>✓ Da, flota activează în ${city}.</strong><br>Dacă te simți pregătit/ă și te tentează, onboarding-ul este doar puțin mai jos.` : `<strong>Momentan nu găsim ${input.value.trim()} în orașele noastre active.</strong><br>Revenim curând cu zone noi.`; if (city) result.innerHTML += '<br><a href="#onboarding" onclick="this.closest(\'dialog\').close()">Mergi la onboarding →</a>'; });
function renderAuth(mode = 'login') { const saved = JSON.parse(localStorage.getItem('ciberoProfile') || 'null'); if (saved) { document.querySelector('#auth-content').innerHTML = `<p class="eyebrow">Contul tău CibeRO</p><h2>Bine ai revenit, ${saved.name}.</h2><div class="auth-success">Cont creat pe acest dispozitiv. După validarea onboarding-ului, parcursul tău și deblocările vor apărea aici.</div><p class="auth-note">În această primă versiune, contul este o demonstrație locală. Activarea reală va fi legată de sistemul onboarding-ului.</p>`; return; } document.querySelector('#auth-content').innerHTML = `<p class="eyebrow">Contul tău CibeRO</p><h2>${mode === 'signup' ? 'Începe parcursul tău.' : 'Bine ai revenit.'}</h2><div class="auth-tabs"><button class="${mode === 'login' ? 'active' : ''}" data-auth-tab="login">Intră în cont</button><button class="${mode === 'signup' ? 'active' : ''}" data-auth-tab="signup">Creează cont</button></div><form id="auth-form">${mode === 'signup' ? '<label for="name">Nume</label><input id="name" required autocomplete="name" placeholder="Numele tău" />' : ''}<label for="email">E-mail</label><input id="email" type="email" required autocomplete="email" placeholder="nume@email.ro" /><label for="password">Parolă</label><input id="password" type="password" required autocomplete="current-password" placeholder="••••••••" /><button class="primary-cta" type="submit">${mode === 'signup' ? 'Creează contul' : 'Intră în cont'} <span>→</span></button></form><p class="auth-note">Momentan construim infrastructura conturilor. Datele din acest prototip sunt păstrate doar în browserul tău, nu pe un server.</p>`; document.querySelectorAll('[data-auth-tab]').forEach(tab => tab.onclick = () => renderAuth(tab.dataset.authTab)); document.querySelector('#auth-form').onsubmit = event => { event.preventDefault(); if (mode === 'signup') localStorage.setItem('ciberoProfile', JSON.stringify({name: document.querySelector('#name').value, email: document.querySelector('#email').value})); document.querySelector('#auth-content').innerHTML = `<p class="eyebrow">Contul tău CibeRO</p><h2>${mode === 'signup' ? 'Cont creat.' : 'Autentificare demonstrativă.'}</h2><div class="auth-success">În versiunea conectată la sistem, aici vei vedea statusul onboarding-ului și deblocările Wolt / Glovo.</div>`; }; }
document.querySelectorAll('[data-open-auth]').forEach(button => button.addEventListener('click', () => { renderAuth(button.dataset.openAuth); authModal.showModal(); }));
document.querySelector('.menu-toggle').addEventListener('click', event => { const nav = document.querySelector('#main-nav'); nav.classList.toggle('open'); event.currentTarget.setAttribute('aria-expanded', nav.classList.contains('open')); });
document.querySelector('[data-onboarding-link]').addEventListener('click', event => { event.preventDefault(); alert('Linkul către flow-ul de onboarding va fi conectat imediat ce îmi trimiți URL-ul lui.'); });
