const views = document.querySelectorAll('.view');
const show = id => { views.forEach(view => view.classList.toggle('active', view.id === id)); window.scrollTo({top:0,behavior:'smooth'}); };
let selectedStatus = '';
document.querySelectorAll('[data-platform]').forEach(button => button.addEventListener('click', () => { if(button.dataset.platform === 'wolt') show('wolt-flow'); else show('glovo-info-flow'); }));
document.querySelectorAll('.platform-card[data-platform]').forEach(card => card.addEventListener('keydown', event => { if(event.key === 'Enter' || event.key === ' ') { event.preventDefault(); card.click(); } }));
document.querySelectorAll('[data-back]').forEach(button => button.addEventListener('click', () => show('platform-step')));
document.querySelectorAll('[data-wolt-back]').forEach(button => button.addEventListener('click', () => { if (statusOptions?.querySelector('[data-status="new"]')) show('wolt-flow'); else resetStatusChoices(); }));
document.querySelectorAll('[data-status-back]').forEach(button => button.addEventListener('click', () => show('status-flow')));
const ruleAccept = document.querySelector('#rule-accept'); const toStatus = document.querySelector('#to-status'); ruleAccept.addEventListener('change', () => toStatus.disabled = !ruleAccept.checked); toStatus.addEventListener('click', () => show('status-flow'));
const detail = document.querySelector('#status-detail');
const details = {courier:`<h3 class="detail-title">Contul tău trebuie transferat în flota noastră.</h3><ol class="detail-steps"><li><b>Asigură-te că ai balanța 0</b>Verifică în aplicația Wolt Courier că nu ai bani neîncasați.</li><li><b>Cere să fii setat Offline</b>Contactează flota actuală și cere setarea Offline.</li><li><b>Cere offboarding</b>Fără offboarding, transferul nu poate fi procesat.</li></ol><p class="detail-warning"><b>Nu completa formularul de înscriere nouă.</b> O înregistrare duplicată poate bloca sau șterge contul existent.</p><button class="continue detail-action">Solicită transferul contului →</button>`,client:`<h3 class="detail-title">Verifică datele înainte să continui.</h3><p>Deschide <b>Wolt Client → Profil → Date personale</b> și verifică emailul, numărul de telefon și numele.</p><label class="accept"><input class="verify-client" type="checkbox" />Am verificat acum datele din aplicația Wolt Client.</label><label class="upload"> <span>▣</span>Încarcă screenshot Wolt Client<input class="proof" type="file" accept="image/*" /></label><button class="continue detail-action to-form" disabled>Continuă cu datele verificate →</button>`,none:`<h3 class="detail-title">Fără cont Wolt Client = activare imposibilă.</h3><p class="detail-warning">Wolt verifică existența unui cont client cu același email și telefon înainte de activare.</p><ol class="detail-steps"><li><b>Descarcă aplicația Wolt Client</b><span>Folosește magazinul potrivit dispozitivului tău.</span><div class="store-links"><a class="store-link play" href="https://play.google.com/store/apps/details?id=com.wolt.android&hl=en" target="_blank" rel="noopener"><i>▶</i>Google Play</a><a class="store-link apple" href="https://apps.apple.com/us/app/wolt-delivery-food-and-more/id943905271" target="_blank" rel="noopener"><i>●</i>App Store</a></div></li><li><b>Creează-ți contul Wolt Client</b>Folosește numele, emailul și telefonul tău real.</li><li><b>Fă un screenshot din Profil → Date personale</b>Numele, emailul și telefonul trebuie să fie vizibile.</li></ol><label class="upload"><span>▣</span>Încarcă screenshot Wolt Client<input class="proof" type="file" accept="image/*" /></label><button class="continue detail-action to-form" disabled>Continuă către formular →</button>`};
details.none = details.none.replace('<div class="store-links"><a class="store-link play" href="https://play.google.com/store/apps/details?id=com.wolt.android&hl=en" target="_blank" rel="noopener"><i>▶</i>Google Play</a><a class="store-link apple" href="https://apps.apple.com/us/app/wolt-delivery-food-and-more/id943905271" target="_blank" rel="noopener"><i>●</i>App Store</a></div>', '<div class="store-links"><a class="store-link play" href="https://play.google.com/store/apps/details?id=com.wolt.android&hl=en" target="_blank" rel="noopener" aria-label="Deschide Wolt Client în Google Play"><img src="https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png" alt="Get it on Google Play" /></a><a class="store-link apple" href="https://apps.apple.com/us/app/wolt-delivery-food-and-more/id943905271" target="_blank" rel="noopener" aria-label="Deschide Wolt Client în App Store"><img src="https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/en-us?size=250x83" alt="Download on the App Store" /></a></div>');
const statusOptions = document.querySelector('.status-options'); const statusTitle = document.querySelector('#status-title'); const statusNote = document.querySelector('#status-note');
const transferDetail = document.querySelector('#transfer-detail');
statusNote.textContent = 'Atenție: conturile deja existente la Wolt influențează procesarea cererii de activare a contului de curier. Verifică atent situația contului tău înainte de a continua.';
new MutationObserver(() => { if (!statusTitle.querySelector('.step-inline')) { const step = statusTitle.textContent.includes('client') ? '3 / 5' : '2 / 5'; statusTitle.insertAdjacentHTML('afterbegin', `<span class="step-inline">${step}</span>`); } }).observe(statusTitle, { childList: true });
const initialStatusOptions = statusOptions.innerHTML;
const resetStatusChoices = () => { selectedStatus = ''; detail.innerHTML = ''; detail.className = 'status-detail'; statusTitle.innerHTML = '<span class="step-inline">2 / 5</span>Ai deja cont activ de <mark class="role-highlight">curier</mark> la Wolt?'; statusNote.textContent = 'Atenție: conturile deja existente la Wolt influențează procesarea cererii de activare a contului de curier. Verifică atent situația contului tău înainte de a continua.'; statusOptions.innerHTML = initialStatusOptions; bindStatusCards(); };
document.querySelectorAll('[data-transfer-back]').forEach(button => button.addEventListener('click', () => { resetStatusChoices(); show('status-flow'); }));
const showClientQuestion = () => { selectedStatus = ''; detail.innerHTML = ''; detail.className = 'status-detail'; statusTitle.innerHTML = 'Ai cont de <mark class="role-highlight">client</mark> Wolt? (din care dai comandă)'; statusNote.textContent = 'Atenție: acest pas este obligatoriu. Conturile de Wolt au influență între ele, conform politicii Wolt.'; statusOptions.innerHTML = `<button class="status-card" data-status="client"><div class="status-card-copy"><b>Da, am cont de client Wolt</b><span class="status-symbol">▣</span><small class="status-action">Verifică datele înainte de formular</small></div><i>○</i></button><button class="status-card" data-status="none"><div class="status-card-copy"><b>Nu, nu am cont de client Wolt</b><span class="status-symbol">✚</span><small class="status-action">Creează contul Wolt Client</small></div><i>○</i></button>`; bindStatusCards(); };
const renderStatus = card => { selectedStatus = card.dataset.status; if (selectedStatus === 'new') { showClientQuestion(); return; } if (selectedStatus === 'courier') { transferDetail.innerHTML = details.courier; transferDetail.className = 'status-detail show transfer-standalone'; show('transfer-flow'); return; } document.querySelectorAll('.status-card').forEach(item => item.classList.toggle('selected',item === card)); detail.innerHTML = details[selectedStatus]; detail.className = `status-detail show branch-${selectedStatus}`; const proof = detail.querySelector('.proof'); const verify = detail.querySelector('.verify-client'); const advance = detail.querySelector('.to-form'); const update = () => { if(advance) advance.disabled = !(proof?.files.length && (!verify || verify.checked)); }; proof?.addEventListener('change', update); verify?.addEventListener('change', update); advance?.addEventListener('click', () => { document.querySelector('#form-description').textContent = selectedStatus === 'client' ? 'Introdu exact datele verificate în Wolt Client.' : 'Introdu datele din contul Wolt Client pe care tocmai l-ai creat.'; show('form-flow'); }); };
const bindStatusCards = () => statusOptions.querySelectorAll('.status-card').forEach(card => card.addEventListener('click', () => renderStatus(card)));
bindStatusCards();
document.querySelector('#wolt-form').addEventListener('submit', event => { event.preventDefault(); show('final-flow'); }); const finalAccept = document.querySelector('#final-accept'); const submit = document.querySelector('#submit-request'); finalAccept.addEventListener('change', () => submit.disabled = !finalAccept.checked); submit.addEventListener('click', () => show('success-flow'));

document.querySelectorAll('[data-glovo-target]').forEach(button => button.addEventListener('click', () => show(button.dataset.glovoTarget)));
document.querySelectorAll('[data-glovo-reveal]').forEach(stack => {
  const items = [...stack.querySelectorAll('.glovo-reveal-item')];
  const button = stack.querySelector('.glovo-next');
  const nextView = stack.dataset.nextView;
  let visible = 1;
  button.addEventListener('click', () => {
    if (visible < items.length) {
      items[visible].classList.add('visible');
      visible += 1;
      button.innerHTML = visible === items.length ? 'Continuă <span>→</span>' : 'Mai departe <span>→</span>';
      return;
    }
    show(nextView);
  });
});
const glovoChecks = [...document.querySelectorAll('.glovo-confirm-card input[type="checkbox"]')];
const glovoConfirmNext = document.querySelector('#glovo-confirm-next');
glovoChecks.forEach(check => check.addEventListener('change', () => { glovoConfirmNext.disabled = !glovoChecks.every(item => item.checked); }));
glovoConfirmNext.addEventListener('click', () => show('glovo-activation-flow'));
document.querySelector('#glovo-form').addEventListener('submit', event => { event.preventDefault(); show('glovo-success-flow'); });
