const links = {
  boltGuide: 'https://www.youtube.com/playlist?list=PLQFx_vtbR0SioPtXeXO2j8aAPaUb3TOYU',
  registration: 'https://controlfleet.ro/onboarding/participatiune/5b2df208d1b9a87844e7fe9508fea2d572d6d9ac503bd2382213a0416f52bb32',
  telegram: 'https://t.me/eatsdelivery_bot?start=onboarding'
};
// Activăm timerele înainte de lansarea finală.
const timersEnabled = false;

const questions = [
  ['Ca și curier nou, ce tipuri de comenzi vei primi?', ['Doar comenzi achitate online de către clienți','Doar comenzi unde curierul colectează cash de la clienți','Doar comenzi cu distanță maximă de 3 km','Toate tipurile de comenzi'], [0]],
  ['Care sunt avantajele comenzilor cash?', ['Posibilitatea de a primi mai mult bacșiș numerar de la clienți','Disponibilitate la mai multe comenzi din mai multe categorii','Rămân cu mai mulți bani pe care îi păstrez'], [0,1]],
  ['Cum ții tips-ul primit cash separat de balanța din aplicație?', ['Schimb suma din balanța numerar după fiecare comandă','Introduc suma fixă de primit de la client; restul rămâne tips-ul meu','Îmi va spune clientul ce să fac'], [1]],
  ['Ce semnifică balanța numerar din aplicație?', ['Suma tuturor tranzacțiilor cash efectuate în activitatea la livrări','Banii pe care îi voi primi la salariu','Toți banii încasați la livrări'], [0]],
  ['Ce semnifică atunci când balanța numerar e afișată cu minus?', ['Administratorul flotei se va ocupa','Bolt Food îmi datorează bani','Datorez bani la Bolt Food și trebuie să-i returnez'], [2]],
  ['Ce se întâmplă dacă ajungi la o sumă mare negativă în balanță?', ['Voi primi mai multe comenzi cu plată la preluare','Contul este blocat complet','Voi fi dat în judecată','Comenzile unde colectez cash sunt blocate până scad sub prag'], [0,3]],
  ['Care este procedura corectă pentru a depune banii cash din balanță?', ['Se ocupă administratorul flotei','Fac transfer bancar folosind datele din aplicație','Îmi pun datele cardului în aplicație și achit direct cu cardul','Voi fi contactat când trebuie depuși'], [2]],
  ['Care metodă de depunere se actualizează cel mai rapid?', ['Transfer bancar','Cu cardul în aplicație','Se ocupă administratorul flotei'], [1]],
  ['Când trebuie să achiți la preluarea unei comenzi de la restaurant?', ['Oricând vreau să îmi reglez balanța','Doar când e indicat în aplicație','Doar când îmi cer cei de la restaurant'], [1]],
  ['Ce ai de făcut la o comandă cash?', ['Plătesc mereu la preluare și colectez mereu de la client','Nu plătesc nimic, dar primesc bani de la client','Plătesc la preluare fără să colectez','Toate variantele, în funcție de indicațiile aplicației'], [3]],
  ['Cum afli că o comandă implică tranzacții cash?', ['Mă informează restaurantul și clientul','Îmi apare înainte să accept','Văd în detaliile comenzii după ce am acceptat-o'], [2]],
  ['Cum afli dacă clientul trebuie să plătească numerar?', ['În detaliile comenzii, după ce am marcat că am ridicat-o','Mă uit în balanță','Clientul îmi arată telefonul'], [0]],
  ['Ce faci când aplicația indică să achiți o sumă la restaurant?', ['Pregătesc suma, o predau, glisez plata și aștept confirmarea restaurantului','Plătesc la POS, iau comanda și plec','Predau suma, iau singur comanda și plec'], [0]],
  ['Ce se întâmplă dacă restaurantul nu confirmă plata în aplicație?', ['Nu pot procesa mai departe comanda și nu apar detaliile clientului','Nu trebuie să confirme','Restaurantul rămâne cu banii și eu cu comanda'], [0]],
  ['Când îți apar informațiile despre client?', ['După ce am ridicat comanda și am marcat preluarea','Imediat după acceptare','Restaurantul mi le oferă după ridicare'], [0]],
  ['Ce faci când predai o comandă cash clientului?', ['Cer banii, îi verific, predau comanda și introduc suma exactă din aplicație; surplusul este tips','Cer banii, predau comanda și introduc toată suma primită'], [0]],
  ['Ce factori influențează reputația contului de curier?', ['Acceptarea, rating-ul, realocarea/anularea și feedback-ul primit','Vehiculul și vremea','Intervalele de lucru și tips-urile'], [0]]
].map(([text, options, correct], id) => ({ id, text, options, correct }));

const calendarQuestions = [
  { text:'Când efectuează flota plățile?', options:['Săptămânal, în fiecare zi de Marți','Săptămânal, în fiecare zi de Vineri după săptămâna lucrată','Lunar, în prima zi a lunii','Lunar, la încheierea fiecărei luni'], correct:1 },
  { text:'Cum calculează Bolt Food săptămânile de lucru?', options:['După calendar: 1–7, 8–15, 16–22, 23–30','Luni la ora 00:00 începe, Duminică la ora 23:59 se încheie','De Vineri până Vineri'], correct:1 }
];

const blank = { screen:'welcome', boltUntil:null, retryUntil:null, boltSet:null, boltQuizIntro:false, boltIntroStep:0, boltIntroWaiting:false, boltPlaylistRevealed:false, boltPlaylistConfirmed:false, guided:{}, equipmentConfirmed:false, equipmentHygiene:false, equipmentTab:'equipment', hygieneConfirmed:false, calendarRevealed:false, calendarUntil:null, calendarConfirmed:false, registrationRevealed:false, registrationVisited:false, registrationUnderstood:false, registrationPrompt:false, registrationReturnConfirmed:false, telegramUntil:null, telegramGuide:null, telegramGuidesDeclined:false, telegramJoined:false };
const guidedLines = {
  bolt:[
    {text:'Deși activăm conturi la mai multe platforme, oferim curierilor activare la Bolt Food în prima fază, pentru o integrare cât mai ușoară și un început cât mai promițător.'},
    {text:'Bolt Food nu doar că este cea mai simplă platformă operațională, dar oferă și cele mai rapide activări la conturile noi - astfel, nu va trebui să aștepți zile, sau săptămâni chiar, pentru activare la alte platforme.'},
    {text:'Ulterior, vei putea cere activare și la alte platforme dacă vei dori.'},
    {text:'Pentru o pregătire cât mai bună, am pregătit un playlist cu 11 video-uri scurte despre Bolt Food. Playlist-ul are aproximativ 10 minute. După ce urmărești playlist-ul, vei avea de completat un quiz.'}
  ],
  equipment:[
    {text:'Pentru a-ți începe activitatea în domeniul de livrări, ai nevoie de o geantă termoizolantă și un vehicul.',html:'Pentru a-ți începe activitatea în domeniul de livrări, ai nevoie de o <mark>geantă termoizolantă</mark> și un <mark>vehicul</mark>.'},
    {text:'Geanta termoizolantă trebuie să fie oficială. O poți achiziționa de pe site-ul Bolt Food Gear.',html:'Geanta termoizolantă trebuie să fie oficială. O poți achiziționa de pe <a href="https://ro.boltfoodgear.com/en/products/bags" target="_blank" rel="noopener">site-ul Bolt Food Gear</a>.'},
    {text:'Poți achiziționa geanta și din alte surse, și poate fi și geantă de Wolt, Glovo sau Tazz. Dar recomandăm să fie într-o stare bună, deoarece igiena e un factor important în acest domeniu.'},
    {tag:'div',text:'Vehiculele admise sunt: Trotinetă electrică. Bicicletă manuală sau electrică. Scuter. Mașină.',html:'<span>Vehiculele admise sunt:</span><ul class="equipment-list"><li>Trotinetă electrică</li><li>Bicicletă manuală sau electrică</li><li>Scuter</li><li>Mașină</li></ul>'},
    {text:'Asigură-te că ai echipamentul necesar și că e într-o stare bună, înainte de a-ți începe activitatea.'}
  ],
  calendar:[{text:'Cu siguranță te interesează ciclul de plată al flotei noastre. Cel mai ușor mod de a-ți oferi aceste informații este printr-un video, explicat direct pe calendar.'}],
  registration:[
    {text:'Trebuie să fii foarte serios dacă ai ajuns până aici...'},
    {text:'Foarte bine - să trecem la etapa de înregistrare atunci!'},
    {text:'Acum că ai informațiile și pregătirea necesară, urmează să completezi înregistrarea în sistemul flotei. Înregistrarea o vei face pe platforma externă a flotei. Acolo îți vei înregistra datele personale pentru deschiderea contului.'},
    {text:'Asigură-te că datele introduse sunt cele personale și corecte.'}
  ],
  telegram:[
    {text:'Comunicarea o desfășurăm pe Telegram. Acolo găsești grupul de comunitate al flotei, canalul special de anunțuri și botul nostru cu informații esențiale, funcții automate și redirecții rapide.'},
    {text:'Pentru a menține comunitatea în siguranță, intrarea în grupurile noastre se face prin intermediul botului nostru. Înainte de aprobare, un admin va verifica manual cererea ta.'},
    {text:'Dacă Telegram e o platformă de mesagerie pe care nu o folosești deja, am pregătit câteva video-uri care să te ghideze în pașii de creare a contului, intrarea în comunitate și utilizarea sistemelor noastre.'}
  ]
};
function playlistPlayer(id,title,firstVideoId=''){const src=firstVideoId?`https://www.youtube.com/embed/${firstVideoId}?list=${id}&index=1`:`https://www.youtube.com/embed/videoseries?list=${id}`;return `<div class="playlist-player"><iframe src="${src}" title="${title}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`}
function videoPlayer(id,title){return `<div class="playlist-player"><iframe src="https://www.youtube-nocookie.com/embed/${id}" title="${title}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`}
const savedSession = JSON.parse(localStorage.getItem('eats-onboarding-v1') || 'null');
let state = { ...blank };
const app = document.querySelector('#app');
const lockTooltip = document.createElement('div');
lockTooltip.id = 'lock-tooltip';
lockTooltip.setAttribute('role','status');
document.body.append(lockTooltip);
function save(){ localStorage.setItem('eats-onboarding-v1', JSON.stringify(state)); }
function go(screen){ state.screen=screen; save(); render(); }
function startFresh(){ state={ ...blank, freshStarted:true }; save(); render(); }
function resume(){ state={ ...blank, ...savedSession }; save(); render(); }
function remaining(until){ return timersEnabled ? Math.max(0, until-Date.now()) : 0; }
function time(ms){ const s=Math.ceil(ms/1000); return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; }
function lockedLabel(label, until){ if(!until || remaining(until)===0) return label; setTimeout(render, 1000); return `${label} · ${time(remaining(until))}`; }
function setProgress(step){ document.querySelectorAll('.step').forEach((item,index)=>{ const current=index===step-1; item.classList.toggle('current',current); item.classList.toggle('complete',index<step-1); item.toggleAttribute('aria-current',current); }); document.querySelectorAll('.step-connector').forEach((line,index)=>line.classList.toggle('complete',index<step-1)); }
function action(label, handler, secondary=false, disabled=false, danger=false, lockHint='Funcția va fi deblocată după ce bifezi căsuța de confirmare'){const button=`<button class="button ${secondary?'secondary':''} ${danger?'danger':''}" ${disabled?'disabled':''} onclick="${handler}">${label}</button>`;return disabled?`<span class="button-lock" tabindex="0" data-lock-message="${lockHint}" onclick="showLockHint(this,event)" onmouseenter="moveLockHint(event,this)" onmousemove="moveLockHint(event,this)" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();showLockHint(this,event)}">${button}</span>`:button;}
function moveLockHint(event,element){if(!event||typeof event.clientX!=='number')return;const width=360;const x=Math.min(event.clientX+14,Math.max(8,window.innerWidth-width));const y=Math.min(event.clientY+16,Math.max(8,window.innerHeight-36));lockTooltip.textContent=element.dataset.lockMessage;lockTooltip.style.left=`${x}px`;lockTooltip.style.top=`${y}px`;lockTooltip.classList.add('visible');}
function showLockHint(element,event){moveLockHint(event,element);lockTooltip.classList.add('persistent');clearTimeout(element.lockHintTimer);element.lockHintTimer=setTimeout(()=>lockTooltip.classList.remove('visible','persistent'),2600);}
document.addEventListener('pointerout',event=>{const lock=event.target.closest?.('.button-lock');const next=event.relatedTarget?.closest?.('.button-lock');if(lock&&lock!==next&&!lockTooltip.classList.contains('persistent'))lockTooltip.classList.remove('visible');});
function ext(label,url,secondary=false){ return `<a class="button ${secondary?'secondary':''}" href="${url}" target="_blank" rel="noopener">${label}</a>`; }
function randomSet(){ return [...questions].sort(()=>Math.random()-.5).slice(0,10).map(q=>q.id); }
function boltReady(){ return (!state.boltUntil || remaining(state.boltUntil)===0) && (!state.retryUntil || remaining(state.retryUntil)===0); }

function welcome(){
  setProgress(1);
  const canResume=!state.freshStarted&&savedSession&&savedSession.screen&&savedSession.screen!=='welcome'&&savedSession.screen!=='done';
  const modal=canResume?`<div class="resume-overlay" role="dialog" aria-modal="true"><div class="resume-dialog"><p>E posibil să fi fost scos din sesiune în timp ce o completai. Vrei să reiei procesul de unde ai rămas în sesiunea anterioară?</p><div class="actions">${action('Da, continui de unde am rămas','resume()')}${action('Nu, reiau procesul de la capăt','startFresh()',true,false,true)}</div></div></div>`:'';
  const benefits=[
    ['◷','Flexibilitate','Tu îți faci programul','dar ține minte că productivitatea se realizează prin disciplină și consistență'],
    ['◈','Autonomie','Ești propriul șef - tu decizi nivelul de muncă și cum o faci','dar sperăm să ții cont de conduita de bun simț și cooperare a platformelor și flotei 🙏'],
    ['◉','Câștiguri competitive','3.000-6.000 lei/lună venit net','noi îți oferim sfaturi, bonusuri și campanii pentru a-ți maximiza profitul - tu decizi unde pui pragul 💪'],
    ['▤','Plăți și rapoarte săptămânale stabile','Încasările tale sunt în siguranță cu noi','primești raport săptămânal și plata direct pe IBAN; plată corectă până la ultimul cent, pentru munca ta 👌'],
    ['◌','Suport dedicat','Staff-ul și comunitatea îți sunt alături','oricând ai probleme, nu ești singur - comunitatea, staff-ul flotei, cât și asistența de la platforme îți sunt alături'],
    ['◇','Siguranță','Un mediu sigur și stabil','datele și activitatea ta din cadrul flotei sunt în siguranță cu noi - adică, ești în siguranță cu noi ✌️'],
    ['✦','Sistemul flotei','Platforme unice, tehnologie intuitivă','avem aplicație mobilă, grup de comunitate, canal de anunțuri, sistem de ticketing și multe altele']
  ];
  const benefitsMarkup=benefits.map(([icon,title,summary,note])=>`<li><span class="benefit-icon">${icon}</span><div><strong>${title}</strong><span>${summary}</span><em class="benefit-note">${note}</em></div></li>`).join('');
  return `<div class="welcome-layout"><div class="welcome-content"><span class="eyebrow">Început</span><h1>Onboarding</h1><p class="lead welcome-intro">Procesul de onboarding e construit în 7 pași. Fiecare pas conține informații și proceduri esențiale în procesul de înscriere și pregătire pentru începerea activității în domeniu.</p><p class="welcome-next-steps">În următorii 7 pași:</p><ul class="welcome-steps"><li>vei învăța despre platforma pe care îți vei începe activitatea;</li><li>vei înțelege care e echipamentul de care ai nevoie pentru a începe;</li><li>vei înțelege care e ciclul de plată;</li><li>te vei înregistra la flota noastră;</li><li>vei intra în grupul de comunitate al flotei, unde desfășurăm comunicarea.</li></ul><p class="quiz-prompt-note welcome-quote">Nu am fi făcut din asta un proces, dacă nu ne-ar fi interesat să ai dinainte tot ce-ți trebuie și să-ți fie mai ușor să te integrezi în acest domeniu și în comunitatea noastră. 👐</p><div class="actions">${action('Începe Onboarding',"go('bolt')")}</div><a class="campaign-teaser" href="https://cibero-riders.github.io/campanii/" target="_blank" rel="noopener"><span class="campaign-teaser-icon" aria-hidden="true">🏆</span><span><strong>Campanii active</strong><small>Curierii activi pot câștiga premii și beneficii suplimentare.</small></span><b>Vezi campaniile <i aria-hidden="true">→</i></b></a></div><aside class="benefits-panel" aria-label="Îți oferim"><h2>Îți oferim:</h2><ul>${benefitsMarkup}</ul></aside></div>${modal}`;
}
function boltQuizPrompt(){return `<div class="resume-overlay quiz-overlay" role="dialog" aria-modal="true"><div class="resume-dialog quiz-dialog"><p>Urmează un Quiz bazat pe informațiile din ghidul video. Intenția este ca tu să ai pregătirea necesară — de aceea:</p><ul class="quiz-rules"><li>Nu e cronometrat și are doar 10 întrebări;</li><li>Ai nevoie de cel puțin 8 răspunsuri corecte;</li><li>Unele întrebări pot avea mai multe răspunsuri corecte;</li><li>Îl poți relua de câte ori ai nevoie;</li><li>Poți urmări ghidul și în timp ce răspunzi.</li></ul><p class="quiz-prompt-note">dacă te vei simți puțin ca la școală, sperăm să trezească și amintirile plăcute</p><p class="quiz-success">Succes! ✌️</p><div class="actions">${action("Hai cu Quiz-u'",'beginBoltQuiz()')}</div></div></div>`}
function guidedProgress(key){const current=state.guided?.[key];if(current)return current;if(key==='bolt')return {step:Math.min(state.boltIntroStep||0,guidedLines.bolt.length),waiting:!!state.boltIntroWaiting};return {step:0,waiting:false};}
function guidedCopy(key){const lines=guidedLines[key];const progress=guidedProgress(key);const completed=Math.min(progress.step||0,lines.length);const staticLines=lines.slice(0,completed).map((line,index)=>{const tag=line.tag||'p';const active=index===completed-1&&(progress.waiting||completed===lines.length);return `<${tag} class="guided-line ${line.className||''} ${active?'is-current':''}">${line.html||line.text}</${tag}>`;}).join('');const typing=completed<lines.length&&!progress.waiting?`<${lines[completed].tag||'p'} class="guided-line ${lines[completed].className||''} is-current guided-typing-line" data-guided-key="${key}"></${lines[completed].tag||'p'}>`:'';const continueButton=completed<lines.length&&progress.waiting?`<button class="continue-reading" onclick="continueGuided('${key}')">Citește în continuare <span aria-hidden="true">→</span></button>`:'';return `${staticLines}${typing}${continueButton}`;}
function guidedComplete(key){return Math.min(guidedProgress(key).step||0,guidedLines[key].length)===guidedLines[key].length;}
function continueGuided(key){const progress=guidedProgress(key);if(!progress.waiting)return;state.guided={...(state.guided||{}),[key]:{...progress,waiting:false}};save();render();}
function finishGuidedLine(key){const lines=guidedLines[key];const progress=guidedProgress(key);const completed=Math.min(progress.step||0,lines.length);if(completed>=lines.length)return;const next=completed+1;state.guided={...(state.guided||{}),[key]:{step:next,waiting:next<lines.length}};save();render();}
function startGuidedTyping(){const target=document.querySelector('[data-guided-key]');if(!target)return;const key=target.dataset.guidedKey;const line=guidedLines[key]?.[Math.min(guidedProgress(key).step||0,guidedLines[key].length)];if(!line||state.screen!==key)return;const reducedMotion=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reducedMotion){target.textContent=line.text;finishGuidedLine(key);return;}let index=0;const write=()=>{if(state.screen!==key||!target.isConnected)return;target.textContent=line.text.slice(0,index);if(index<line.text.length){index+=1;setTimeout(write,18);return;}finishGuidedLine(key);};write();}
function normalizeConfirmationLabels(){document.querySelectorAll('.video-confirmation span,.registration-confirmation span').forEach(item=>{const calendarLabel='Am urmărit video-ul și am înțeles ciclul de plată al flotei.';item.textContent=item.textContent===calendarLabel?'Am urmărit video-ul și am înțeles care e ciclul de plată':item.textContent.replace(/\.$/,'');});}
const originalStartGuidedTyping=startGuidedTyping;
startGuidedTyping=function(){normalizeConfirmationLabels();originalStartGuidedTyping();};
function bolt(){ setProgress(2); const active=state.boltUntil && remaining(state.boltUntil)>0; const contentUnlocked=guidedComplete('bolt'); const playlistContent=state.boltPlaylistRevealed?`${playlistPlayer('PLQFx_vtbR0SioPtXeXO2j8aAPaUb3TOYU','Ghidul Curierului la Bolt Food')}<div class="notice"><strong>Mulți curieri omit informarea și întâmpină probleme ulterior. Petrece câteva minute să te informezi - salvează mai mult timp pe urmă. 😌</strong></div><label class="video-confirmation bolt-playlist-confirmation"><input type="checkbox" ${state.boltPlaylistConfirmed?'checked':''} onchange="confirmBoltPlaylist(this.checked)"><span>Am urmărit playlist-ul și am informațiile necesare pentru a face quiz-ul.</span></label><div class="actions">${action(lockedLabel('Începe Quiz-ul',state.boltUntil),"startBolt()",false,active||!state.boltPlaylistConfirmed)}</div>`:`<button class="continue-reading playlist-reveal" onclick="revealBoltPlaylist()">Afișează playlist-ul ghid <span aria-hidden="true">→</span></button>`; return `<span class="eyebrow">Pasul 2 · Bolt Food</span><h1>Introducere la Bolt Food.</h1><div class="guided-copy">${guidedCopy('bolt')}</div>${contentUnlocked?`<div class="guided-reveal">${playlistContent}</div>`:''}${state.boltQuizIntro?boltQuizPrompt():''}`; }
function revealBoltPlaylist(){state.boltPlaylistRevealed=true;save();render();}
function confirmBoltPlaylist(confirmed){state.boltPlaylistConfirmed=confirmed;save();render();}
function startBolt(){ if(!boltReady()||!state.boltPlaylistConfirmed)return; state.boltSet=randomSet(); state.boltAnswers={}; state.boltResult=null; state.boltQuizIntro=true; save(); render(); }
function beginBoltQuiz(){ state.boltQuizIntro=false; go('boltQuiz'); }
function boltQuiz(){ setProgress(2); let set=(state.boltSet||randomSet()).map(id=>questions[id]).filter(Boolean); if(set.length!==10){state.boltSet=randomSet();state.boltAnswers={};state.boltResult=null;set=state.boltSet.map(id=>questions[id]);} state.boltSet=set.map(q=>q.id); save(); const done=state.boltResult; return `<span class="eyebrow">Pasul 2 · Quiz Bolt Food</span><ul class="bolt-quiz-instructions"><li>Ai nevoie de <strong>8/10 răspunsuri corecte</strong> pentru a merge mai departe.</li><li>Toate întrebările sunt strict din playlist-ul ghid de la pasul anterior.</li><li>Poți alege mai multe răspunsuri prin selecție multiplă.</li></ul>${set.map((q,i)=>question(q,i,true,done)).join('')} ${done?boltOutcome():`<div class="actions">${action('Finalizează Quiz-ul','submitBolt()',false,!allAnswered(set),false,'Selectează cel puțin un răspuns la fiecare întrebare pentru a putea finaliza quiz-ul')}</div>`}`; }
function question(q,n,multi,result){ const chosen=(state.boltAnswers||{})[q.id]||[]; return `<fieldset class="question"><legend>${n+1}. ${q.text}</legend><div class="options">${q.options.map((o,i)=>{ const cls=result ? (q.correct.includes(i)?'correct':chosen.includes(i)?'incorrect':'') : ''; return `<label class="option ${cls}"><input ${result?'disabled':''} type="${multi?'checkbox':'radio'}" name="q${q.id}" value="${i}" ${chosen.includes(i)?'checked':''} onchange="selectBolt(${q.id},${i},${multi})"><span>${o}</span></label>` }).join('')}</div>${result&&!same(chosen,q.correct)?`<p class="answer-note">Răspuns corect: ${q.correct.map(i=>q.options[i]).join(' · ')}</p>`:''}</fieldset>`; }
function selectBolt(id,index,multi){ const a=state.boltAnswers||{}; const now=a[id]||[]; a[id]=multi?(now.includes(index)?now.filter(x=>x!==index):[...now,index]):[index]; state.boltAnswers=a; save(); render(); }
function same(a,b){ return a.length===b.length && a.every(x=>b.includes(x)); }
function allAnswered(set){ return set.every(q=>(state.boltAnswers||{})[q.id]?.length); }
function submitBolt(){ const set=state.boltSet.map(id=>questions[id]); if(!allAnswered(set))return; state.boltResult=set.filter(q=>same(state.boltAnswers[q.id],q.correct)).length; save(); render(); }
function boltOutcome(){ const score=state.boltResult; if(score>=8) return `<div class="result"><h2>Ai trecut quiz-ul!</h2><p>Ai răspuns corect la <strong>${score}/10</strong> întrebări. Măi să fie, înseamnă că ai ce-ți trebuie. Atunci, nu te mai reținem. Felicitări! 👏</p><div class="actions proud-action"><span>simte mândria și</span>${action('mergi mai departe',"go('equipment')")}</div></div>`; if(!state.retryUntil&&timersEnabled){state.retryUntil=Date.now()+300000;save();} const active=state.retryUntil&&remaining(state.retryUntil)>0; return `<div class="result fail"><h2>Mai încearcă o dată.</h2><p>Ai răspuns corect la <strong>${score}/10</strong> întrebări. Urmărește din nou ghidul și încearcă din nou cu mai multă atenție.</p><div class="actions">${ext('Deschide din nou ghidul',links.boltGuide,true)}${action(lockedLabel('Reia Quiz-ul',state.retryUntil),'retryBolt()',false,active)}</div></div>`; }
function retryBolt(){ if(state.retryUntil&&remaining(state.retryUntil)>0)return; state.retryUntil=null; state.boltUntil=null; state.boltSet=randomSet(); state.boltAnswers={}; state.boltResult=null; save(); render(); }
function equipmentTabs(){
  const hygiene=state.equipmentTab==='hygiene';
  const tabs=`<div class="equipment-tabs" role="tablist" aria-label="Conținutul pasului Echipament"><button class="equipment-tab ${!hygiene?'is-active':''}" type="button" role="tab" aria-selected="${!hygiene}" onclick="selectEquipmentTab('equipment')"><span class="equipment-tab-check" aria-hidden="true">✓</span>Echipament</button><button class="equipment-tab ${hygiene?'is-active':''}" type="button" role="tab" aria-selected="${hygiene}" onclick="selectEquipmentTab('hygiene')">Norme de igienă</button></div>`;
  const equipmentPanel=`<section class="equipment-tab-panel equipment-complete-panel" role="tabpanel"><div class="equipment-tab-heading"><span aria-hidden="true">✓</span><div><h2>Echipament confirmat</h2><p>Geanta termoizolantă și vehiculul sunt confirmate. Următorul tab conține regulile aplicabile la fiecare livrare.</p></div></div><p class="equipment-tab-transition">Normele de igienă se confirmă înainte de trecerea la pasul 4 · Plăți.</p><div class="actions">${action('Vezi normele de igienă',"selectEquipmentTab('hygiene')")}</div></section>`;
  const hygienePanel=`<section class="equipment-tab-panel hygiene-panel" role="tabpanel"><div class="equipment-tab-heading"><span class="hygiene-symbol" aria-hidden="true">✦</span><div><h2>Norme de igienă</h2><p>Nu trebuie să prepari tu mâncarea - însă tu o transporți, iar normele de igienă sunt importante, precum sunt și pentru bucătari.</p></div></div><p class="hygiene-notice">Transportarea comenzilor se face doar într-o geantă termoizolantă oficială, curată, uscată, funcțională și care se poate închide complet.</p><div class="hygiene-rules"><section><h3>Înainte de livrare</h3><ul><li>Verifică geanta: curată, uscată, fără mirosuri și deteriorări</li><li>Igienizează mâinile și poartă îmbrăcăminte curată</li><li>Nu păstra obiecte personale sau produse murdare în geantă</li></ul></section><section><h3>La preluare și transport</h3><ul><li>Verifică ambalajele; nu deschide produsele sigilate</li><li>Fixează recipientele vertical și separă băuturile când poți</li><li>Protejează comanda de ploaie, praf, soare și manevre bruște</li></ul></section><section><h3>După livrare / incident</h3><ul><li>Curăță imediat scurgerile și dezinfectează geanta</li><li>Predă comanda doar clientului și marcheaz-o livrată după predare</li><li>Raportează comenzile deteriorate, vărsate sau imposibil de predat</li></ul></section></div><div class="hygiene-official-note" role="note"><span aria-hidden="true">⚠</span><p>Informațiile prezentate mai sus sunt doar cele generale. Pentru o informare completă, deschide <a href="https://script.google.com/macros/s/AKfycbypcf0B_qtH8gfaLjaHu7pjuLabSqM6cSrAhr0UsDEwToM3E9peh-wj92FcwoBee0ksGA/exec" target="_blank" rel="noopener">Documentul oficial cu normele de igienă</a> și asigură-te că le cunoști înainte de a-ți începe activitatea.</p></div><label class="video-confirmation hygiene-confirmation"><input type="checkbox" ${state.hygieneConfirmed?'checked':''} onchange="confirmHygiene(this.checked)"><span>Am citit și voi respecta normele de igienă în timpul livrărilor</span></label><div class="actions">${action('Mergi la Plăți',"go('calendar')",false,!state.hygieneConfirmed)}</div></section>`;
  return `<div class="equipment-tabs-card guided-reveal">${tabs}${hygiene?hygienePanel:equipmentPanel}</div>`;
}
function equipment(){ setProgress(3); const contentUnlocked=guidedComplete('equipment'); const initialContent=`<div class="guided-reveal"><div class="notice equipment-notice"><div class="equipment-alert"><span aria-hidden="true">⚠</span><strong>Odată ce contul tău e activ, nu vei putea livra dacă nu ai echipamentul necesar.</strong></div></div><label class="video-confirmation equipment-confirmation"><input type="checkbox" ${state.equipmentConfirmed?'checked':''} onchange="confirmEquipment(this.checked)"><span>Am echipamentul necesar și voi putea începe imediat ce primesc activarea contului</span></label><div class="actions">${action('Mergi mai departe','openHygiene()',false,!state.equipmentConfirmed)}</div></div>`; return `<span class="eyebrow">Pasul 3 · Echipament</span><h1>Echipamentul necesar.</h1>${state.equipmentHygiene?equipmentTabs():`<div class="guided-copy">${guidedCopy('equipment')}</div>${contentUnlocked?initialContent:''}`}`; }
function confirmEquipment(confirmed){state.equipmentConfirmed=confirmed;save();render();}
function openHygiene(){if(!state.equipmentConfirmed)return;state.equipmentHygiene=true;state.equipmentTab='hygiene';save();render();}
function selectEquipmentTab(tab){state.equipmentTab=tab;save();render();}
function confirmHygiene(confirmed){state.hygieneConfirmed=confirmed;save();render();}
function calendar(){ setProgress(4); const active=state.calendarUntil&&remaining(state.calendarUntil)>0; const contentUnlocked=guidedComplete('calendar'); const calendarContent=state.calendarRevealed?`<div class="notice calendar-note"><strong>Urmărește video-ul de dedesubt, iar după ce ai înțeles ciclul de plată, continuă la pașii următori. Mai sunt doar 2 pași pentru finalizare.</strong></div>${videoPlayer('iBThwch_Tn0','Calendarul de Plată Eats Delivery')}<label class="video-confirmation"><input type="checkbox" ${state.calendarConfirmed?'checked':''} onchange="confirmCalendarVideo(this.checked)"><span>Am urmărit video-ul și am înțeles ciclul de plată al flotei.</span></label><div class="actions">${action(lockedLabel('Mergi mai departe',state.calendarUntil),"go('calendarQuiz')",false,active||!state.calendarConfirmed)}</div>`:`<button class="continue-reading calendar-reveal" onclick="revealCalendar()">Afișează calendarul de plată <span aria-hidden="true">→</span></button>`; return `<span class="eyebrow">Pasul 4 · Plăți</span><h1>Calendarul de plată.</h1><div class="guided-copy">${guidedCopy('calendar')}</div>${contentUnlocked?`<div class="guided-reveal">${calendarContent}</div>`:''}`; }
function revealCalendar(){state.calendarRevealed=true;save();render();}
function confirmCalendarVideo(confirmed){state.calendarConfirmed=confirmed;save();render()}
function calendarQuiz(){ setProgress(4); const done=state.calendarResult; const complete=calendarQuestions.every((_,i)=>Number.isInteger(state.calendarAnswers?.[i])); return `<span class="eyebrow">Pasul 4 · Quiz Calendar</span><div class="notice calendar-quiz-note"><p class="quiz-prompt-note calendar-quiz-aside">Nu vrei să știi câți noi veniți întreabă pe grupuri „când e plata” după ce completează onboarding-ul.</p><strong>Așadar, răspunde la cele două întrebări. Nu te teme, nu e quiz. E doar o reîmprospătare rapidă a memoriei. Vei vedea pe urmă răspunsurile corecte, fără restricții și fără alte rețineri. Valorificăm timpul prețios.</strong></div>${calendarQuestions.map((q,i)=>calendarQuestion(q,i,done)).join('')}${done?`<div class="actions">${action('Mergi mai departe',"go('registration')")}</div>`:`<div class="actions">${action('Verifică răspunsurile','submitCalendar()',false,!complete)}</div>`}`; }
function calendarQuestion(q,n,done){const v=state.calendarAnswers?.[n];return `<fieldset class="question"><legend>${n+1}. ${q.text}</legend><div class="options">${q.options.map((o,i)=>`<label class="option ${done ? (i===q.correct ? 'correct' : i===v ? 'incorrect' : '') : ''}"><input type="radio" name="cal${n}" ${done?'disabled':''} ${i===v?'checked':''} onchange="selectCalendar(${n},${i})"><span>${o}</span></label>`).join('')}</div>${done&&v!==q.correct?`<p class="answer-note">Răspuns corect: ${q.options[q.correct]}</p>`:''}</fieldset>`}
function selectCalendar(n,v){state.calendarAnswers=state.calendarAnswers||[];state.calendarAnswers[n]=v;save();render();} function submitCalendar(){state.calendarResult=true;save();render();}
function registered(){state.registrationVisited=true;state.registrationPrompt=false;save();render();}
function confirmRegistrationReturn(confirmed){state.registrationUnderstood=confirmed;save();render();}
function openRegistrationReminder(){if(!state.registrationUnderstood)return;state.registrationPrompt=true;state.registrationReturnConfirmed=false;save();render();}
function confirmRegistrationReminder(confirmed){state.registrationReturnConfirmed=confirmed;save();render();}
function goToRegistration(){if(!state.registrationReturnConfirmed)return;window.open(links.registration,'_blank','noopener');registered();}
const telegramGuides=[
  {id:'juBx-JwoBaA',title:'Cum îți creezi cont pe Telegram'},
  {id:'44GbSXgUQV0',title:'Cum intri în comunitatea flotei'},
  {id:'D1gdobmjeDY',title:'Cum folosești sistemul nostru de pe Telegram'}
];
function chooseTelegramGuide(id){state.telegramGuide=id;state.telegramGuidesDeclined=false;save();render()}
function moreTelegramGuides(){state.telegramGuide=null;state.telegramGuidesDeclined=false;save();render()}
function skipTelegramGuides(){state.telegramGuide=null;state.telegramGuidesDeclined=true;save();render()}
function telegramJoined(){state.telegramJoined=true;save();render()}
function registration(){setProgress(5);const reminder=state.registrationPrompt?`<div class="resume-overlay" role="dialog" aria-modal="true" aria-label="Confirmare înainte de înregistrare"><div class="resume-dialog registration-dialog"><p>După înregistrare, nu uita să revii la această pagină pentru a completa și ultimul pas.</p><label class="registration-confirmation"><input type="checkbox" ${state.registrationReturnConfirmed?'checked':''} onchange="confirmRegistrationReminder(this.checked)"><span>Am înțeles - după înregistrare revin aici pentru finalizarea completă a onboarding-ului.</span></label><div class="actions">${action('Mergi la înregistrare','goToRegistration()',false,!state.registrationReturnConfirmed)}</div></div></div>`:'';const contentUnlocked=guidedComplete('registration');const registrationContent=state.registrationRevealed?`<div class="registration-data-warning" role="note"><span aria-hidden="true">⚠</span><p>Nu introduce datele altcuiva, deoarece riști să nu primești aprobare.</p></div><div class="notice registration-note"><div class="registration-attention-title"><span aria-hidden="true">⚠</span><strong>Atenție!</strong></div><p>După ce completezi înregistrarea pe site-ul extern, e necesar să te întorci aici pentru a completa și ultimul pas: accesul în grupul nostru de Telegram unde desfășurăm comunicarea.</p></div><label class="registration-confirmation"><input type="checkbox" ${state.registrationUnderstood?'checked':''} onchange="confirmRegistrationReturn(this.checked)"><span>Am înțeles că după înregistrare trebuie să revin la această pagină pentru a intra în grupul flotei.</span></label><div class="actions">${state.registrationVisited?action('Acces în grupul flotei',"go('telegram')"):action('Înregistrează-te','openRegistrationReminder()',false,!state.registrationUnderstood)}</div>`:`<button class="continue-reading registration-reveal" onclick="revealRegistration()">Așa facem <span aria-hidden="true">→</span></button>`;return `<span class="eyebrow">Pasul 5 · Înregistrare</span><h1>Înregistrează-te în sistem.</h1><div class="guided-copy">${guidedCopy('registration')}</div>${contentUnlocked?`<div class="guided-reveal">${registrationContent}</div>`:''}${reminder}`}
function revealRegistration(){state.registrationRevealed=true;save();render();}
function telegram(){setProgress(6);const active=state.telegramUntil&&remaining(state.telegramUntil)>0;const guide=telegramGuides.find(item=>item.id===state.telegramGuide);const guideArea=state.telegramGuidesDeclined?'':guide?`${videoPlayer(guide.id,guide.title)}<div class="guide-followup"><p>Mai ai nevoie de și alt ghid Telegram înainte de a finaliza onboarding-ul?</p><div class="actions">${action('Da','moreTelegramGuides()',true)}${action('Nu','skipTelegramGuides()',true,false,true)}</div></div>`:`<div class="telegram-guides"><span class="guide-label">GHIDURI PENTRU TELEGRAM</span>${telegramGuides.map((item,index)=>action(`${index+1}. ${item.title}`,`chooseTelegramGuide('${item.id}')`,true)).join('')}</div>`;const finalAction=`<div class="actions telegram-final-action">${action(lockedLabel('Finalizează onboarding-ul',state.telegramUntil),"go('done')",false,active||!state.telegramJoined,false,'Funcția va fi deblocată după ce intri pe Telegram')}</div>`;const contentUnlocked=guidedComplete('telegram');return `<span class="eyebrow">Pasul 6 · Comunitate</span><h1>Alătură-te comunității flotei pe Telegram</h1><div class="guided-copy">${guidedCopy('telegram')}</div>${contentUnlocked?`<div class="guided-reveal">${guideArea}<div class="actions telegram-community-action"><a class="button telegram-community-button" href="${links.telegram}" target="_blank" rel="noopener" onclick="telegramJoined()">Alătură-te comunității pe Telegram</a></div>${finalAction}</div>`:''}`}
function done(){setProgress(7);return `<div class="final"><div class="check">✓</div><span class="eyebrow">Onboarding finalizat</span><h1>Mulțumim!</h1><p class="lead">Cererea ta a fost înregistrată. Vei primi curând următorii pași, referitori la activare.</p><p>Îți urăm bun venit și sperăm să fie o colaborare cât mai reușită, de toate părțile!</p><a class="campaign-completion" href="https://cibero-riders.github.io/campanii/" target="_blank" rel="noopener"><span class="campaign-active"><i aria-hidden="true"></i>CAMPANII ACTIVE</span><span class="campaign-completion-copy"><strong>Transformă-ți activitatea în premii și beneficii.</strong><small>Descoperă campania Veteran și Tombola săptămânală.</small></span><b>Vezi campaniile active <i aria-hidden="true">→</i></b></a><p class="final-close-note"><span aria-hidden="true">✓</span> Poți închide această pagină.</p></div>`}
function render(){if(state.screen==='boltQuiz'&&state.boltQuizIntro){state.screen='bolt';save()}if(timersEnabled&&state.screen==='bolt'&&!state.boltUntil){state.boltUntil=Date.now()+300000;save()}if(timersEnabled&&state.screen==='calendar'&&!state.calendarUntil){state.calendarUntil=Date.now()+180000;save()}if(timersEnabled&&state.screen==='telegram'&&!state.telegramUntil){state.telegramUntil=Date.now()+120000;save()}app.classList.toggle('intro-card',state.screen==='welcome');app.innerHTML=({welcome,bolt,boltQuiz,equipment,calendar,calendarQuiz,registration,telegram,done}[state.screen]||welcome)();startGuidedTyping();}
function focusActiveMobileStep(){if(!window.matchMedia?.('(max-width: 780px)').matches)return;const stepper=document.querySelector('.cibero-stepper');const current=stepper?.querySelector('.step.current');if(!stepper||!current)return;const left=Math.max(0,current.offsetLeft-(stepper.clientWidth-current.offsetWidth)/2);stepper.scrollTo({left,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
const baseRender=render;
render=function(){baseRender();requestAnimationFrame(focusActiveMobileStep);};
render();
