const API_URL = "https://xpzgvknnrkyvcnncfqrq.supabase.co/functions/v1/submit-social-registration";
const PUBLISHABLE_KEY = "sb_publishable_yqSB3WMkNNxujsJhLMqLJA_8Q99BmbN";
const cities = ["Alba Iulia","Arad","Bacău","Baia Mare","Botoșani","Brăila","Brașov","București","Buzău","Cluj-Napoca","Constanța","Craiova","Deva","Drobeta-Turnu Severin","Focșani","Galați","Hunedoara","Iași","Mediaș","Miercurea-Ciuc","Onești","Oradea","Piatra Neamț","Pitești","Ploiești","Râmnicu Vâlcea","Reșița","Roman","Satu Mare","Sfântu Gheorghe","Sibiu","Sighișoara","Slatina","Suceava","Târgoviște","Târgu Mureș","Tecuci","Timișoara","Tulcea","Vaslui","Zalău"];
const copy = {
  ro:{eyebrow:"CibeRO · ÎNREGISTRARE",title:"Înscriere Curier",intro:"Alătură-te rețelei noastre de livrare și începe să câștigi.",courierType:"Ce tip de colaborare cauți?",newCourier:"Curier nou",experienced:"Curier cu experiență",fullName:"Nume complet",fullNamePlaceholder:"Ion Popescu",email:"Email",phone:"Telefon",nationality:"Naționalitate",nationalityPlaceholder:"Română",city:"Oraș",vehicle:"Tip vehicul",source:"De unde ai aflat de noi?",intent:"Ce vrei să faci?",intentHint:"Descrie pe scurt",intentPlaceholder:"Ex: Vreau să lucrez la Glovo; Am PFA și vreau 5 curieri; Avem SRL cu 10 mașini...",platforms:"Selectează platformele",adult:"Confirm că am cel puțin 18 ani.",privacy:"Sunt de acord cu procesarea datelor mele personale pentru analizarea acestei înregistrări.",submit:"Trimite înregistrarea",sending:"Se trimite…",success:"Înregistrarea ta a fost trimisă. Te vom contacta cât mai curând.",successEyebrow:"CibeRO · ÎNREGISTRARE CONFIRMATĂ",successTitle:"Înregistrarea a fost trimisă!",successText:"Am primit datele tale. Echipa CibeRO le va analiza și te va contacta cât mai curând.",successNote:"Păstrează telefonul și emailul disponibile pentru a putea reveni rapid către tine.",home:"Întoarce-te la pagina principală",platformError:"Selectează cel puțin o platformă.",error:"Înregistrarea nu a putut fi trimisă. Încearcă din nou.",chooseCity:"Selectează orașul",chooseVehicle:"Selectează tipul",chooseSource:"Selectează sursa",vehicles:["Bicicletă","Bicicletă electrică","Scuter","Trotinetă electrică","Mașină"],sources:[["facebook","Facebook"],["instagram","Instagram"],["tiktok","TikTok"],["youtube","YouTube"],["google","Google"],["other","Altă sursă"]]},
  en:{eyebrow:"CibeRO · REGISTRATION",title:"Courier Registration",intro:"Join our delivery network and start earning.",courierType:"What type of collaboration are you looking for?",newCourier:"New courier",experienced:"Experienced courier",fullName:"Full name",fullNamePlaceholder:"John Doe",email:"Email",phone:"Phone",nationality:"Nationality",nationalityPlaceholder:"Romanian",city:"City",vehicle:"Vehicle type",source:"How did you hear about us?",intent:"What would you like to do?",intentHint:"Describe briefly",intentPlaceholder:"E.g. I want to work with Glovo; I have a PFA and need 5 couriers; We have an SRL with 10 cars...",platforms:"Choose platforms",adult:"I confirm that I am at least 18 years old.",privacy:"I agree to the processing of my personal data to assess this registration.",submit:"Send registration",sending:"Sending…",success:"Your registration was sent. We will contact you shortly.",successEyebrow:"CibeRO · REGISTRATION CONFIRMED",successTitle:"Registration sent!",successText:"We have received your details. The CibeRO team will review them and contact you shortly.",successNote:"Keep your phone and email available so we can get back to you quickly.",home:"Return to the home page",platformError:"Choose at least one platform.",error:"The registration could not be sent. Please try again.",chooseCity:"Choose city",chooseVehicle:"Choose vehicle",chooseSource:"Choose source",vehicles:["Bicycle","Electric bicycle","Scooter","Electric scooter","Car"],sources:[["facebook","Facebook"],["instagram","Instagram"],["tiktok","TikTok"],["youtube","YouTube"],["google","Google"],["other","Another source"]]}
};
let language = "ro";
const form = document.querySelector("#social-registration-form");
const feedback = document.querySelector("#form-feedback");
const submit = document.querySelector("#submit-registration");
const registrationIntake = document.querySelector("#registration-intake");
const registrationSuccess = document.querySelector("#registration-success");
const citySelect = document.querySelector("#city-select");
const vehicleSelect = document.querySelector("#vehicle-select");
const sourceSelect = document.querySelector("#source-select");
const escapeHtml = value => String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function options(select, placeholder, values) { select.innerHTML = `<option value="" selected disabled>${escapeHtml(placeholder)}</option>${values.map(([value,label]) => `<option value="${escapeHtml(value)}">${escapeHtml(label)}</option>`).join("")}`; }
function render() { const t=copy[language]; document.documentElement.lang=language; document.querySelectorAll("[data-i18n]").forEach(node=>node.textContent=t[node.dataset.i18n]); document.querySelectorAll("[data-i18n-placeholder]").forEach(node=>node.placeholder=t[node.dataset.i18nPlaceholder]); document.querySelectorAll("[data-language]").forEach(button=>button.classList.toggle("active",button.dataset.language===language)); options(citySelect,t.chooseCity,cities.map(city=>[city,city])); options(vehicleSelect,t.chooseVehicle,["Bicicletă","Bicicletă electrică","Scuter","Trotinetă electrică","Mașină"].map((value,index)=>[value,t.vehicles[index]])); options(sourceSelect,t.chooseSource,t.sources); }
document.querySelectorAll("[data-language]").forEach(button=>button.addEventListener("click",()=>{language=button.dataset.language;render();}));
form.addEventListener("submit",async event=>{event.preventDefault();feedback.textContent="";feedback.classList.remove("success");const selected=[...form.querySelectorAll('input[name="platforms"]:checked')];if(!selected.length){feedback.textContent=copy[language].platformError;return;}if(!form.reportValidity())return;submit.disabled=true;submit.textContent=copy[language].sending;try{const body=new FormData(form);body.set("adult_confirmed",body.get("adult_confirmed")?"true":"false");body.set("consent_privacy",body.get("consent_privacy")?"true":"false");const response=await fetch(API_URL,{method:"POST",headers:{apikey:PUBLISHABLE_KEY},body});const result=await response.json().catch(()=>({}));if(!response.ok||!result.ok)throw new Error(result.error||copy[language].error);form.reset();registrationIntake.hidden=true;registrationSuccess.hidden=false;window.scrollTo({top:0,behavior:"smooth"});}catch(error){feedback.textContent=error.message||copy[language].error;}finally{submit.disabled=false;submit.textContent=copy[language].submit;}});
render();
