(() => {
  const translations = {
    heroKicker:'CIBERO · COURIER HUB',heroTitle:'Everything you need for courier work, in one place.',heroLead:'Clear information, quick access to support and fleet tools — ready when you need them.',ticketButton:'Open a ticket',exploreButton:'Explore the tools',liveInfo:'AUTOMATICALLY UPDATED',nextPayment:'Next payment window',workPeriod:'Work period',paymentNote:'Payments for the previous week are usually made on Thursday or Friday. The exact date may vary.',toolsKicker:'QUICK ACCESS',toolsTitle:'How can we help?',toolsIntro:'The most-used information and actions, without searching through old conversations.',supportTitle:'Support and requests',supportBody:'Payments, accounts, documents, reimbursements and other situations.',campaignsTitle:'Campaigns',campaignsBody:'See active campaigns and their conditions.',benefitsTitle:'Benefits',benefitsBody:'Reimbursement, consultancy and sole trader collaboration.',platformsTitle:'Platform guide',platformsBody:'Compare Bolt Food, Glovo and Wolt.',onboardingTitle:'Onboarding',onboardingBody:'Everything you need before activation.',knowledgeKicker:'QUICK LIBRARY',knowledgeTitle:'Useful rules, by platform.',knowledgeIntro:'Select a platform to see relevant cash and balance information.',allPlatforms:'All',platformSelector:'Select platform',boltTitle:'Balance and deposits',boltRule1:'Deposit the full balance by Sunday, 23:59.',boltRule2:'We do not recommend exceeding a negative balance of 500 RON.',boltRule3:'Deposit directly by card in Bolt Courier.',glovoTitle:'Cash and balance',glovoRule1:'Deposit the full balance by Sunday, 23:59.',glovoRule2:'At a negative balance of 500 RON, you can no longer receive orders.',glovoRule3:'Deposit at any SelfPay station.',woltTitle:'Cash and reset day',woltRule1:'Deposit the full balance on every Wolt-specific reset day.',woltRule2:'At 500 RON in balance, you cannot go online until it is fully covered.',woltRule3:'Deposit through Aircash.',communityKicker:'STAY CONNECTED',communityTitle:'The CibeRO community is on WhatsApp.',communityBody:'General discussions and help between couriers are in the community group. Important news is published separately in the announcements channel.',communityButton:'Community group',announcementsButton:'Announcements channel',nextKicker:'COMING TO THE HUB',nextTitle:'A personal account for every member.',nextIntro:'This area will be connected after we define authentication and migrate data from the Telegram system.',profileTitle:'Verified profile',profileBody:'Phone, city, platforms and seniority, protected by authentication.',requestsTitle:'Requests and status',requestsBody:'Data updates, approvals and history in one flow.',remindersTitle:'Personal reminders',remindersBody:'Preferences for payments, reset dates and WhatsApp notifications.',versionNote:'This is the first informational version of the Hub. It does not yet collect or display personal data.'
  };
  const nodes=[...document.querySelectorAll('[data-hub-i18n]')];
  const originals=new Map(nodes.map(node=>[node,node.textContent]));
  const ariaNodes=[...document.querySelectorAll('[data-hub-i18n-aria]')];
  const ariaOriginals=new Map(ariaNodes.map(node=>[node,node.getAttribute('aria-label')]));
  const description=document.querySelector('meta[name="description"]');
  const originalDescription=description?.content;
  let language=document.documentElement.lang==='en'?'en':'ro';
  const formatDate=date=>new Intl.DateTimeFormat(language==='en'?'en-GB':'ro-RO',{day:'numeric',month:'long',timeZone:'Europe/Bucharest'}).format(date);
  function getPaymentDates(){
    const now=new Date(); const date=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate(),12));
    let days=(4-date.getUTCDay()+7)%7; if(days===0&&now.getHours()>=18)days=7;
    const thursday=new Date(date); thursday.setUTCDate(date.getUTCDate()+days);
    const friday=new Date(thursday); friday.setUTCDate(thursday.getUTCDate()+1);
    const periodEnd=new Date(thursday); periodEnd.setUTCDate(thursday.getUTCDate()-4);
    const periodStart=new Date(periodEnd); periodStart.setUTCDate(periodEnd.getUTCDate()-6);
    return{thursday,friday,periodStart,periodEnd};
  }
  function renderPayment(){const d=getPaymentDates();document.querySelector('[data-payment-window]').textContent=`${formatDate(d.thursday)} – ${formatDate(d.friday)}`;document.querySelector('[data-payment-period]').textContent=`${formatDate(d.periodStart)} – ${formatDate(d.periodEnd)}`;}
  function setLanguage(next){language=next==='en'?'en':'ro';nodes.forEach(node=>node.textContent=language==='en'?(translations[node.dataset.hubI18n]||originals.get(node)):originals.get(node));ariaNodes.forEach(node=>node.setAttribute('aria-label',language==='en'?(translations[node.dataset.hubI18nAria]||ariaOriginals.get(node)):ariaOriginals.get(node)));document.title=language==='en'?'CIBERO Hub | Courier tools':'CIBERO Hub | Instrumente pentru curieri';if(description)description.content=language==='en'?'CIBERO Hub — information, tools and quick access for CibeRO couriers.':originalDescription;renderPayment();}
  document.addEventListener('cibero:language-change',event=>setLanguage(event.detail.language));
  document.querySelectorAll('[data-platform]').forEach(button=>button.addEventListener('click',()=>{const platform=button.dataset.platform;document.querySelectorAll('[data-platform]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active));});document.querySelectorAll('[data-rule-platform]').forEach(card=>card.hidden=platform!=='all'&&card.dataset.rulePlatform!==platform);}));
  setLanguage(document.documentElement.lang);
})();
